export const SET_DATA_DIAGNOSTIC = 'SET_DATA_DIAGNOSTIC';
export const SET_DATA_FINISHED = 'SET_DATA_FINISHED';
export const SET_DATA_RESULT = 'SET_DATA_RESULT';
export const SET_DONE = 'SET_DONE';
export const SET_URL = 'SET_URL';
export const SET_APPOINTMENT_MESSAGE = 'SET_APPOINTMENT_MESSAGE';
export const TOGGLE_ENABLED = 'TOGGLE_ENABLED';
export const SET_DETAILS = 'SET_DETAILS';

export const CREATE_SOURCE = 'CREATE_SOURCE';
export const PAYMENT_DONE = 'PAYMENT_DONE';

export const CONSULTATION_TABLE = 'CONSULTATION_TABLE';
export const CONSULTATION_TABLE_OFFSET = 'CONSULTATION_TABLE_OFFSET';
export const CONSULTATION_TABLE_STATUS = 'CONSULTATION_TABLE_STATUS';

export const LINK_CONSULT_MESSAGE = 'LINK_CONSULT_MESSAGE';
export const LINK_CONSULT_DETAILS = 'LINK_CONSULT_DETAILS';
export const DONE_LINK_CONSULT_MESSAGE = 'DONE_LINK_CONSULT_MESSAGE';
export const CONSULT_INFO = 'CONSULT_INFO';
