export const SET_DATA_DIAGNOSTIC = 'SET_DATA_DIAGNOSTIC';
export const SET_DATA_FINISHED = 'SET_DATA_FINISHED';
export const SET_DATA_RESULT = 'SET_DATA_RESULT';
export const SET_DONE = 'SET_DONE';
export const SET_URL = 'SET_URL';
export const SET_APPOINTMENT_MESSAGE = 'SET_APPOINTMENT_MESSAGE';
export const TOGGLE_ENABLED = 'TOGGLE_ENABLED';
