export const SET_DOCTOR = 'SET_DOCTOR';
export const SET_DOCTOR_BY_SPECIALTY = 'SET_DOCTOR_BY_SPECIALTY';

export const SET_SPECIALTY = 'SET_SPECIALTY';
export const SET_DOCTOR_INFO = 'SET_DOCTOR_INFO';
