export const GET_GENERATOR_REGULAR = 'GET_GENERATOR_REGULAR';
export const GET_COUNTER_QUEUE = 'GET_COUNTER_QUEUE';
export const SET_COUNTER = 'SET_COUNTER';
export const GET_WAITING_QUEUE = 'GET_WAITING_QUEUE';
export const GET_USER_QUEUE_NUMBER = 'GET_USER_QUEUE_NUMBER';
export const GET_GENERATED_NUMBER = 'GET_GENERATED_NUMBER';
