export const SET_SERVICES = 'SET_SERVICES';
export const SET_IMAGE_SERVICES = 'SET_IMAGE_SERVICES';

export const SET_SERVICES_INFO = 'SET_SERVICES_INFO';

export const GET_SERVICES_DESC = 'GET_SERVICES_DESC';
export const GET_SERVICES_INFO = 'GET_SERVICES_INFO';
export const GET_SERVICE_ID = 'GET_SERVICE_ID';
export const GET_SERVICE_INFO_ID = 'GET_SERVICE_INFO_ID';
