require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Premiere' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'RNCPicker', :path => '../node_modules/@react-native-picker/picker'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'react-native-progress-bar-android', :path => '../node_modules/@react-native-community/progress-bar-android'

  pod 'react-native-progress-view', :path => '../node_modules/@react-native-community/progress-view'

  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  pod 'RNPDF', :path => '../node_modules/react-native-view-pdf'

  pod 'react-native-fingerprint-scanner', :path => '../node_modules/react-native-fingerprint-scanner'

  pod 'react-native-text-input-mask', :path => '../node_modules/react-native-text-input-mask'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  target 'PremiereTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Premiere-tvOS' do
  # Pods for Premiere-tvOS

  target 'Premiere-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
